@startuml

actor RandomAccessFile
actor art.bmp

activate RandomAccessFile
RandomAccessFile -> art.bmp : read (signature)

activate art.bmp
alt response is .bmp
return .bmp
art.bmp -> art.bmp : readInt(ra);


RandomAccessFile -> art.bmp : seek()
art.bmp --> RandomAccessFile  : seek(0x12) 

else some other signature
deactivate RandomAccessFile 

end

@enduml

